version: "3.7"
services:
  devices:
    build: ./devices/
    environment:
      - CONFIG=/src/config.json
      - DATAPATH=/data
      - LOGLEVEL=INFO
    privileged: true
    restart: always
    volumes:
      - /home/pi/air-trend/config.json:/src/config.json:ro
      - /dev/serial:/dev/serial
      - /home/pi/data:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
