#!/bin/bash
# Ben Fasoli

/usr/bin/screen -S metone-es642 -dm /home/uataq/air-trend/log/src/metone-es642.py
/usr/bin/screen -S teledyne-t200 -dm /home/uataq/air-trend/log/src/teledyne-t200.py
/usr/bin/screen -S teledyne-t300 -dm /home/uataq/air-trend/log/src/teledyne-t300.py
/usr/bin/screen -S teledyne-t300-3161 -dm /home/uataq/air-trend/log/src/teledyne-t300-3161.py
/usr/bin/screen -S teledyne-t400 -dm /home/uataq/air-trend/log/src/teledyne-t400.py
#/usr/bin/screen -S teom-1400ab -dm /home/uataq/air-trend/log/src/teom-1400ab.py
